-- SCRIPT TO CREATE ADMIN USER
CREATE USER 'admin'@'localhost'	IDENTIFIED BY 'Adm1n.01';
CREATE USER 'admin'@'%'		IDENTIFIED BY 'Adm1n.01';

-- GRANT ALL PERMISSIONS
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';

-- RELOAD PERMISSIONS
FLUSH PRIVILEGES;

